first_project/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    url(r'^$', views.SchoolListView.as_view(),name='list'),
    url(r'^(?P<pk>\d+)/$',views.SchoolDetailView.as_view(),name='detail'),
    url(r'^create/$',views.SchoolCreateView.as_view(),name='create'),
    url(r'^update/(?P<pk>\d+)/$',views.SchoolUpdateView.as_view(),name='update'),
    url(r'^delete/(?P<pk>\d+)/$',views.SchoolDeleteView.as_view(),name='delete'),
]

first_project/first_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from basic_app import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^basic_app/',include('basic_app.urls',namespace='basic_app')),
    url(r'^$', views.IndexView.as_view()),
    # grabs our class and show it as a view
]

first_project/basic_app/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def get_absolute_url(self):
        return reverse("basic_app:detail",kwargs={'pk':self.pk})

    def __str__(self):
        return self.name

class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School,related_name='students')

    def __str__(self):
        return self.name

first_project/basic_app/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse_lazy
from django.views.generic import (View, TemplateView,
                                ListView,DetailView,
                                CreateView,UpdateView,
                                DeleteView)

from . import models

class IndexView(TemplateView):
    template_name = 'index.html'

    # to create a context dictionary for injecting data into templates
    def get_context_data(self,**kwargs):
        # passing in self and keyword arguments
        context = super().get_context_data(**kwargs)
        context['injection'] = 'display this message on the index page'
        return context

class SchoolListView(ListView):
    model = models.School
    # template_name = 'basic_app/school_list.html' <- this is the default template name
    # this returns a context dictionary named school_list
    # lowercase model name underscore list, (snake_case)
    # we can change the name of this context dictionary like so
    # context_object_name = 'schools'

class SchoolDetailView(DetailView):
    # context_object_name by default will just return school (lowercase model name)
    # context_object_name = 'school_detail' (we can of course, manually define our context_object_name)
    model = models.School
    template_name = 'basic_app/school_detail.html'


class SchoolCreateView(CreateView):
    fields = ('name','principal','location')
    model = models.School

class SchoolUpdateView(UpdateView):
    fields = ("name","principal")
    model = models.School

class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("basic_app:list")

first_project/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <ul class="nav navbar-nav">
        <li class='navbar-link'><a href="{% url 'basic_app:list' %}">Schools list</a></li>
        <li class='navbar-link'><a href="{% url 'admin:index' %}">Admin</a></li>
      </ul>
    </nav>

    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>

  </body>
</html>

first_project/basic_app/templates/basic_app/school_confirm_delete.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}

<h1>Delete: {{school.name}}</h1>
<form class="" method="POST">
  {% csrf_token %}
  <input type="submit" class="btn btn-danger" value="Delete school">
  <a href="{% url 'basic_app:detail' pk=school.pk %}">Cancel</a>
</form>

{% endblock %}

first_project/basic_app/templates/basic_app/school_detail.html
<!DOCTYPE html>
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}
  <div class="jumbotron">
    <h2>School details:</h2>
    <p>Id_num: {{school.id}}</p>
    <p>Name: {{school.name}}</p>
    <p>Principal: {{school.principal}}</p>
    <p>Location: {{school.location}}</p>
    <h3>Students:</h3>
    {% for student in school.students.all %}
      <p>{{student.name}} who is {{student.age}} years old</p>
    {% endfor %}
  </div>

  <div class="container">
    <p>
      <a class='btn btn-warning' href="{% url 'basic_app:update' pk=school.pk %}">Update</a>
      <a class='btn btn-danger' href="{% url 'basic_app:delete' pk=school.pk %}">Delete</a>
    </p>

  </div>

{% endblock %}

first_project/basic_app/templates/basic_app/school_form.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}

  <h1>
    {% if not form.instance.pk %}
    <!-- does an instance of this primary key exist?  -->
    <!-- if not... create one. if so, update it -->
    Create School
    {% else %}
    Update School
    {% endif %}
  </h1>
    <form method="POST">
      {% csrf_token %}
      {{form.as_p}}
      <input type="submit" class="btn btn-primary" value="Create School">
    </form>

{% endblock %}

first_project/basic_app/templates/basic_app/school_list.html
<!DOCTYPE html>
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}
  <div class="jumbotron">
    <h1>This is our school list file</h1>
      <ol>
        {% for school in school_list %}
          <h3><li><a href="{{school.id}}">{{school.name}}</a></li></h3>
        {% endfor %}
      </ol>
  </div>
  <div class="container">
    <p><a href="{% url 'basic_app:create' %}">Create a new school</a></p>
  </div>
{% endblock %}

first_project/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <ul class="nav navbar-nav">
        <li class='navbar-link'><a href="{% url 'basic_app:list' %}">Schools list</a></li>
        <li class='navbar-link'><a href="{% url 'admin:index' %}">Admin</a></li>
      </ul>
    </nav>

    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>

  </body>
</html>

first_project/templates/index.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Template view served up by a class in our views.py file</h1>
    <h2>how to do template injection with class based views:  {{injection}}</h2>
    <h3>also serving as the home page</h3>
  </div>
{% endblock %}